Repository ikhsan3adi/c5-jump-and-survive, pull requests merged in 2025-03, with the labels that each got.

#5 Perbaikan modul `Game`
  include/game.h
  src/game.c
  src/main.c
Labels: enhancement, perbaikan kecil, perbaikan besar

#6 Add game state management system
  include/game_state.h
  src/game_state.c
Labels: fitur-baru

#7 Update game_state.h
  include/game_state.h
Labels: perbaikan besar

#8 Fix game_state.h
  include/game_state.h
Labels: perbaikan kecil, perbaikan besar

#9 Fix game `initialize` return value
  src/game.c
Labels: perbaikan kecil

#14 Feat/entity and physics
  include/collision.h
  include/entity.h
  include/game_state.h
  include/level0_state.h
  include/level1_state.h
  include/menu_state.h
  include/physics.h
  include/player.h
  include/transform.h
  src/collision.c
  src/entity.c
  src/level0_state.c
  src/level1_state.c
  src/main.c
  src/menu_state.c
  src/physics.c
  src/player.c
Labels: fitur-baru, perbaikan besar

#16 merge the latest main changes
  include/collision.h
  include/entity.h
  include/game_state.h
  include/level0_state.h
  include/level1_state.h
  include/menu_state.h
  include/physics.h
  include/player.h
  include/transform.h
  src/collision.c
  src/entity.c
  src/level0_state.c
  src/level1_state.c
  src/main.c
  src/menu_state.c
  src/physics.c
  src/player.c
Labels: fitur-baru

#21 Update `game-stat` branch with `tile-system`
  include/entity.h
  include/level.h
  include/level0_state.h
  include/level1_state.h
  include/player.h
  include/stage0_state.h
  include/stage1_state.h
  src/entity.c
  src/game.c
  src/level.c
  src/menu_state.c
  src/physics.c
  src/player.c
  src/stage0_state.c
  src/stage1_state.c
Labels: help wanted

#24 Update & improve `ui`
  src/menu_state.c
Labels: tampilan/style

#28 Menambahkan asset SFX
  assets/SFX/bg-music-home.mp3
  assets/SFX/bg-music-home1.mp3
  assets/SFX/bg-music1.mp3
  assets/SFX/bg-music2.mp3
  assets/SFX/coins.mp3
  assets/SFX/correct-2-46134.mp3
  assets/SFX/dead.mp3
  assets/SFX/exit-gate.mp3
  assets/SFX/game-over-39-199830.mp3
  assets/SFX/game-over.mp3
  assets/SFX/platform-sound.mp3
Labels: fitur-baru
